spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:gestion-neumaticos-db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres123}

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=10

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

logging.level.ar.edu.utn.frsf.pfc.niclemeichtry.gestion_neumaticos=DEBUG
logging.level.org.hibernate.SQL=DEBUG
